name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build 
        uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo build --release


      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: target/x86_64-unknown-linux-musl/release/kvs3
          args: --lzma
          strip: true

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Get CHANGELOG.md entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/kvs3
          tag: ${{ github.ref }}
          asset_name: kvs3-$tag-linux-x86_64
          body: ${{ steps.changelog_reader.outputs.log_entry }}
